### ISSUE TITLE
Provide REST API for linting pkix certificates i.e. lint_pkix_cert

### ISSUE THREAD

**Issue by dipaktilekar** [digicert/pkilint#118]
**Add support for pkix cert in below GET APIs:** 

> - /certificate
> - /certificate/{linter_group_name}
> - /certificate/{linter_group_name}/{linter_name}
> 

**Add support for pkix cert in below POST APIs**: 

> - /certificate/{linter_group_name}
> - /certificate/{linter_group_name}/{linter_name}

FYI - @CBonnell

**Comment by CBonnell** [comment]
Thanks for filing this. I agree that this would be useful to add.

For `linter_group_name`, I think "pkix" would be clear. For `linter_name`, since pkilint has only one linter for PKIX certificates, calling this linter `certificates` is appropriate. More linters with specific names can be added in the future as such linters are added.

Concretely:

1. GET `/certificate/pkix` returns the single PKIX linter
2. GET `/certificate/pkix/certificate` returns the list of validations performed by the PKIX certificate linter
3. POST `/certificate/pkix` "detects" and lints a certificate with the PKIX certificate linter (since there's only one PKIX linter, there's nothing to detect, but the endpoint will be consistent with the SMBR and TLSBR API endpoints)
4. POST `/certificate/pkix/certificate` lints a certificate with the PKIX certificate linter

@dipaktilekar does this sound like a good approach?

**Comment by dipaktilekar** [comment]
@CBonnell yes, this is a good approach.

**Comment by CBonnell** [comment]
> In that case GET /certificate/pkix/certificate will match REST pattern /certificate/{linter_group_name}/{linter_name} and will consider certificate as the linter. So do we want to call PKIX linter as certificate instead of certificates ?

Yes, I think that makes sense for consistency.
